kind: Service
apiVersion: v1
metadata:
  name: {{ name }}
spec:
  selector:
    app: {{ name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ port|default(80) }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ name }}
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      imagePullSecrets:
        - name: {{ name }}
      containers:
      - name: {{ name }}
        image: {{ image }}
        workingDir: {{ workingDir|default('/') }}
        command: {{ command|default(['python', 'project/main.py']) }}
        ports:
        - containerPort: {{ port|default(80) }}
        env:
        {% for key, value in env.items() -%}
        - name: {{ key }}
          value: {{ value }}
        {% endfor -%}
        volumeMounts:
        {% for key, value in pvcmounts.items() -%}
        - name: pvc-{{loop.index}}
          {% if key|path -%}
          subPath: {{ key|path }}
          {% endif -%}
          mountPath: {{ value }}
        {% endfor -%}
        resources:
          requests:
            cpu: {{ cpu|default(0.5) }}
          limits:
            cpu: {{ cpu|default(0.5) }}
      volumes:
      {% for key, value in pvcmounts.items() -%}
      - name: pvc-{{loop.index}}
        persistentVolumeClaim:
          claimName: {{ key|base }}
{% endfor -%}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ name }}
  minReplicas: {{ minReplicas | default(1) }}
  maxReplicas: {{ maxReplicas | default(8) }}
  targetCPUUtilizationPercentage: 50
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ name }}
  annotations:
    #nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/add-base-url: "True"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"

spec:
  rules:
  - host: {{ host }}
    http:
      paths:
      - backend:
          serviceName: {{ name }}
          servicePort: 80
        {% if path is defined -%}
        path: {{ path }}
        {% endif -%}
